### ISSUE TITLE
Añadir estructura del proyecto

### ISSUE THREAD

**Issue by Yaamiilaa** [colidom/proyecto-ets#10]
No se encuentran las carpetas dedicadas al despliegue, source y testing.

**Comment by colidom** [comment]
La estructura de carpetas que se ve en el repositorio no sigue la convención que comentas porque hacemos uso de un [Framework](https://es.wikipedia.org/wiki/Framework) que un poco lo que busca es proporcionar un entorno de trabajo que no es más que una **estructura conceptual y tecnológica de asistencia definida** de ahí que tengamos el proyecto se estructure de esta manera.

Básicamente todo el proyecto cuelga de una carpeta llamada **app/nombre_de_la_app** y ahí podemos encontrar todas las subcarpetas que componen toda la estructura de la app:

Como podrás ver dentro de esta estructura antes mencionada contamos con una carpeta llamada:
- **/testing** -> Contiene los tests de la aplicación.
- **/static** -> Contiene los ficheros estáticos del sitio, img, css, etc.
- **/templates** -> Contiene los ficheros HTML de la aplicación.


Saludos
Att: Carlos
