### ISSUE TITLE
Añadir README.md

### ISSUE THREAD

**Issue by Yaamiilaa** [colidom/proyecto-ets#11]
Se debe añadir un README a la carpeta doc con la información del proyecto con su respectivo índice, y en el índice los enlaces que llevan a las carpetas o a los archivos que contiene la dicha carpeta.

**Comment by colidom** [comment]
Lo teníamos hecho en la propia tarjeta #4. Gracias por informar, lo hemos añadido a su correspondiente fichero README.md dentro de la carpeta doc ;)
