### ISSUE TITLE
Corregir diagrama caso de uso

### ISSUE THREAD

**Issue by Yaamiilaa** [colidom/proyecto-ets#12]
El orden de los casos de uso está mal estructurado. <3

**Comment by colidom** [comment]
Ampliar información por favor <3 ;)

**Comment by Yaamiilaa** [comment]
La flecha que va de administrador a peluquero está al revés y el administrador tiene que estar autenticado para poder realizar todas sus tareas. <3 ;)

**Comment by colidom** [comment]
Se corrige diagrama según indicaciones. 

![Image](https://user-images.githubusercontent.com/30834486/233661681-b2fde3d0-633a-4fe3-a0b0-c737e441bda6.jpg)
