### ISSUE TITLE
Corregir diagrama entidad relación #9

### ISSUE THREAD

**Issue by Yaamiilaa** [colidom/proyecto-ets#14]
En el diagrama no están especificados las claves primarias de todas las entidades, además, faltan claves primarias en algunas. 
En la entidad "app" no encontramos sentido a los atributos "register" y "login". Por otro lado, los atributos "schedule" y "examples" tendrían sentido si fueran entidades. Además, el atributo "barber contact" tendría que ir en la entidad "barber" ya que en la entidad "app" no entendemos que es.

**Comment by YerobeGG** [comment]
Cambios realizados en ES-Modelo_entidad_relacion y EN-Model_entity_relation acorde a el comentario.
