### ISSUE TITLE
Crear un login en HTML/CSS para la aplicación

### ISSUE THREAD

**Issue by YerobeGG** [colidom/proyecto-ets#8]
**Vamos a empezar a crear algo grafico para el cliente haciendo un login con HTML/CSS diseñado por nostros mismo como una fase previa y a la que podremos realizar cambios a futuro.**

**Comment by colidom** [comment]
Lo he revision y me parece que está guay, solo que miraría hacer el logo un poquito más grande para darle un poco más de representación y miraría que el diseño fuera un poco más responsive, al usar dispositivos de inferior tamaño se desencaja un poco el diseño.
